/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PhotoCaption = {
  _type: "photoCaption";
  caption?: string;
  narrative?: string;
  intent?: "personal" | "editorial" | "portfolio" | "social" | "work";
  isPublic?: boolean;
  isSensitive?: boolean;
  copyright?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PhotoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "photo";
};

export type Gallery = {
  _id: string;
  _type: "gallery";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  photos?: Array<
    {
      _key: string;
    } & PhotoReference
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  nicknames?: Array<string>;
  slug?: Slug;
  roles?: Array<string>;
  portrait?: PhotoReference;
  bio?: string;
  appearancesNote?: string;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type GalleryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "gallery";
};

export type Photo = {
  _id: string;
  _type: "photo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  slug?: Slug;
  context?: PhotoCaption;
  associations?: {
    capturedDate?: string;
    people?: Array<
      {
        _key: string;
      } & PersonReference
    >;
    location?: LocationReference;
    tags?: Array<
      {
        _key: string;
      } & TagReference
    >;
    galleries?: Array<
      {
        _key: string;
      } & GalleryReference
    >;
  };
  referencedIn?: Array<
    {
      _key: string;
    } & GalleryReference
  >;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  city?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PhotoCaption
  | SanityImageAssetReference
  | PhotoReference
  | Gallery
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Tag
  | Person
  | PersonReference
  | LocationReference
  | TagReference
  | GalleryReference
  | Photo
  | Location
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../frontend/src/sanity/queries.ts
// Variable: ADMIN_QUERY
// Query: *[_type == "adminProfile"][0]{  userHandle,  systemRole,  bio,  socialLinks,  "identity": idenity->{    name,    image,    roles,    bio,    connections  }}
export type ADMIN_QUERY_RESULT = null;

// Source: ../frontend/src/sanity/queries.ts
// Variable: PUBLIC_PHOTOS_QUERY
// Query: *[_type == "photo" && context.isPublic == true && context.isSensitive != true]   | order(_createdAt desc) {      _id,  "slug": slug.current,  image { asset->{ _id, metadata { lqip, palette, dimensions, exif } } },  context { caption, narrative, intent, isPublic, isSensitive },  "associations": {    "dateConfig": years[0]->{ title }, // Mapping reference to 'year' schema    "location": locations[0]->{ _id, name, city },    "people": people[]->{ _id, name, "slug": slug.current },    "tags": tags[]->{ _id, title, "slug": slug.current }  }  }
export type PUBLIC_PHOTOS_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      metadata: {
        lqip: string | null;
        palette: SanityImagePalette | null;
        dimensions: SanityImageDimensions | null;
        exif: null;
      } | null;
    } | null;
  } | null;
  context: {
    caption: string | null;
    narrative: string | null;
    intent: "editorial" | "personal" | "portfolio" | "social" | "work" | null;
    isPublic: boolean | null;
    isSensitive: boolean | null;
  } | null;
  associations: {
    dateConfig: null;
    location: null;
    people: null;
    tags: null;
  };
}>;

// Source: ../frontend/src/sanity/queries.ts
// Variable: PERSON_BY_SLUG_QUERY
// Query: *[_type == "person" && slug.current == $slug][0]{  _id,  name,  "slug": slug.current,  image,  roles,  bio,  connections,  "associatedPhotos": *[_type == "photo" && references(^._id) && context.isPublic == true]{      _id,  "slug": slug.current,  image { asset->{ _id, metadata { lqip, palette, dimensions, exif } } },  context { caption, narrative, intent, isPublic, isSensitive },  "associations": {    "dateConfig": years[0]->{ title }, // Mapping reference to 'year' schema    "location": locations[0]->{ _id, name, city },    "people": people[]->{ _id, name, "slug": slug.current },    "tags": tags[]->{ _id, title, "slug": slug.current }  }  }}
export type PERSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  image: null;
  roles: Array<string> | null;
  bio: string | null;
  connections: null;
  associatedPhotos: Array<{
    _id: string;
    slug: string | null;
    image: {
      asset: {
        _id: string;
        metadata: {
          lqip: string | null;
          palette: SanityImagePalette | null;
          dimensions: SanityImageDimensions | null;
          exif: null;
        } | null;
      } | null;
    } | null;
    context: {
      caption: string | null;
      narrative: string | null;
      intent: "editorial" | "personal" | "portfolio" | "social" | "work" | null;
      isPublic: boolean | null;
      isSensitive: boolean | null;
    } | null;
    associations: {
      dateConfig: null;
      location: null;
      people: null;
      tags: null;
    };
  }>;
} | null;

// Source: ../frontend/src/sanity/queries.ts
// Variable: INDIVIDUAL_PHOTO_QUERY
// Query: *[_type == "photo" && slug.current == $slug][0] {      _id,  "slug": slug.current,  image { asset->{ _id, metadata { lqip, palette, dimensions, exif } } },  context { caption, narrative, intent, isPublic, isSensitive },  "associations": {    "dateConfig": years[0]->{ title }, // Mapping reference to 'year' schema    "location": locations[0]->{ _id, name, city },    "people": people[]->{ _id, name, "slug": slug.current },    "tags": tags[]->{ _id, title, "slug": slug.current }  }  }
export type INDIVIDUAL_PHOTO_QUERY_RESULT = {
  _id: string;
  slug: string | null;
  image: {
    asset: {
      _id: string;
      metadata: {
        lqip: string | null;
        palette: SanityImagePalette | null;
        dimensions: SanityImageDimensions | null;
        exif: null;
      } | null;
    } | null;
  } | null;
  context: {
    caption: string | null;
    narrative: string | null;
    intent: "editorial" | "personal" | "portfolio" | "social" | "work" | null;
    isPublic: boolean | null;
    isSensitive: boolean | null;
  } | null;
  associations: {
    dateConfig: null;
    location: null;
    people: null;
    tags: null;
  };
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "adminProfile"][0]{\n  userHandle,\n  systemRole,\n  bio,\n  socialLinks,\n  "identity": idenity->{\n    name,\n    image,\n    roles,\n    bio,\n    connections\n  }\n}': ADMIN_QUERY_RESULT;
    '\n  *[_type == "photo" && context.isPublic == true && context.isSensitive != true] \n  | order(_createdAt desc) {\n    \n  _id,\n  "slug": slug.current,\n  image { asset->{ _id, metadata { lqip, palette, dimensions, exif } } },\n  context { caption, narrative, intent, isPublic, isSensitive },\n  "associations": {\n    "dateConfig": years[0]->{ title }, // Mapping reference to \'year\' schema\n    "location": locations[0]->{ _id, name, city },\n    "people": people[]->{ _id, name, "slug": slug.current },\n    "tags": tags[]->{ _id, title, "slug": slug.current }\n  }\n\n  }\n': PUBLIC_PHOTOS_QUERY_RESULT;
    '*[_type == "person" && slug.current == $slug][0]{\n  _id,\n  name,\n  "slug": slug.current,\n  image,\n  roles,\n  bio,\n  connections,\n  "associatedPhotos": *[_type == "photo" && references(^._id) && context.isPublic == true]{\n    \n  _id,\n  "slug": slug.current,\n  image { asset->{ _id, metadata { lqip, palette, dimensions, exif } } },\n  context { caption, narrative, intent, isPublic, isSensitive },\n  "associations": {\n    "dateConfig": years[0]->{ title }, // Mapping reference to \'year\' schema\n    "location": locations[0]->{ _id, name, city },\n    "people": people[]->{ _id, name, "slug": slug.current },\n    "tags": tags[]->{ _id, title, "slug": slug.current }\n  }\n\n  }\n}': PERSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "photo" && slug.current == $slug][0] {\n    \n  _id,\n  "slug": slug.current,\n  image { asset->{ _id, metadata { lqip, palette, dimensions, exif } } },\n  context { caption, narrative, intent, isPublic, isSensitive },\n  "associations": {\n    "dateConfig": years[0]->{ title }, // Mapping reference to \'year\' schema\n    "location": locations[0]->{ _id, name, city },\n    "people": people[]->{ _id, name, "slug": slug.current },\n    "tags": tags[]->{ _id, title, "slug": slug.current }\n  }\n\n  }\n': INDIVIDUAL_PHOTO_QUERY_RESULT;
  }
}
